# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         svmgraph
version:      0.01
version_from: bin/svmgraph
installdirs:  site
requires:
    GraphViz:                      1.99
    Solaris::Disk::SVM:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
